name: Trading Signal Bot
on:
  schedule:
    - cron: '*/12 * * * *'  # Run every 12 minutes (5x/hour)
  workflow_dispatch:  # Manual trigger option

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install yfinance python-binance requests python-telegram-bot pandas
        
    - name: Run trading bot
      run: python trading_bot.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
