name: Trading Bot
on: 
  schedule:
    - cron: '0 * * * *'  # Every hour at :00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: pip install python-telegram-bot==13.7 yfinance pandas
      
      - name: Run bot
        run: python trading_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
