name: Telegram Test
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Secrets
        run: |
          echo "Token exists: ${{ secrets.TELEGRAM_TOKEN != '' }}"
          echo "Token preview: ${{ secrets.TELEGRAM_TOKEN != '' && '***' + secrets.TELEGRAM_TOKEN[:3] + '...' + secrets.TELEGRAM_TOKEN[-3:] + '***' || 'NOT SET' }}"
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - run: pip install python-telegram-bot==20.3
      
      - run: python trading_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
