name: Telegram Bot Test
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Hourly at :00

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify Secrets
        run: |
          echo "Token exists: ${{ secrets.TELEGRAM_TOKEN != '' }}"
          echo "Chat ID exists: ${{ secrets.CHAT_ID != '' }}"
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - run: pip install python-telegram-bot==13.7
      
      - run: python trading_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
