name: Telegram Connection Test
on: workflow_dispatch

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Secrets
        run: |
          echo "Token exists: ${{ secrets.TELEGRAM_TOKEN != '' }}"
          echo "Token starts with: ${{ secrets.TELE_TOKEN != '' && secrets.TELEGRAM_TOKEN[:3] || 'NONE' }}"
          echo "Chat ID exists: ${{ secrets.CHAT_ID != '' }}"
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - run: pip install python-telegram-bot==13.7
      
      - run: python trading_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
