name: Trading Signal Bot
on:
  schedule:
    - cron: '*/12 * * * *'  # Every 12 minutes (5x/hour)
  workflow_dispatch:        # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10     # Prevent hanging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libatlas-base-dev gfortran
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install yfinance python-binance requests python-telegram-bot pandas numpy TA-Lib
        
    - name: Run trading bot
      run: python trading_bot.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        
    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: trading-logs
        path: |
          *.log
          *.txt
